name: Build

on: [pull_request, push]

jobs:
    build:
        name: Build - PHP ${{ matrix.php-versions }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: [ '7.2', '7.3', '7.4', '8.0', '8.1', '8.2' ]
        steps:
            -   name: Setup PHP, with composer and extensions
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}

            -   uses: actions/checkout@v1

            -   name: Validate composer.json and composer.lock
                run: |
                    composer clear-cache
                    composer validate

            -   name: Install dependencies
                run: |
                    composer install --prefer-dist --no-progress --no-suggest

            -   name: PHP Stan
                run: |
                    composer run phpstan

            -   name: PHP Unit
                run: |
                    composer run phpunit
